//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Runtime Version: 4.0.30319.34003
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE H7}
{$HIDE W1}
{$HIDE W27}
{$HIDE H11}

namespace EnterpriseWebApplication;

interface

type
    _Default = public partial class
    protected 
        var form1: System.Web.UI.HtmlControls.HtmlForm;
        var Label1: System.Web.UI.WebControls.Label;
    end;
    
implementation

end.
